version: "3.7"
services:
  workspace:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PHP_VERSION: "7.4"
        COMPOSER_VERSION: "2.3.3"
        INSTALL_XDEBUG: ${INSTALL_XDEBUG}
        XDEBUG_VERSION: 3.1.0
    user: 1000:1000
    environment:
      XDEBUG_CONFIG: $XDEBUG_CONFIG
      PHP_IDE_CONFIG: "serverName=phpstorm"
    volumes:
      - .:/usr/src/myapp
    entrypoint: [ "sh", "-c" ]
    command: [ "
      tail -f /dev/null
    " ]